// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD445GrCBmV3uFqC0fngMD4LKO8WFxuSjg',
    appId: '1:138743338203:web:d853d981887e8cae6028fe',
    messagingSenderId: '138743338203',
    projectId: 'beestore-ytu-9e44b',
    authDomain: 'beestore-ytu-9e44b.firebaseapp.com',
    storageBucket: 'beestore-ytu-9e44b.appspot.com',
    measurementId: 'G-KEBNTGL13G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRnQM5627G0v_GeHU28XPhw7FYbEOAOE',
    appId: '1:138743338203:android:3034ca4f1f9b46746028fe',
    messagingSenderId: '138743338203',
    projectId: 'beestore-ytu-9e44b',
    storageBucket: 'beestore-ytu-9e44b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDCYH9zBWW_LXObnrJF2waHhHtcFnqEsI',
    appId: '1:138743338203:ios:e6790edf89a75a1b6028fe',
    messagingSenderId: '138743338203',
    projectId: 'beestore-ytu-9e44b',
    storageBucket: 'beestore-ytu-9e44b.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDCYH9zBWW_LXObnrJF2waHhHtcFnqEsI',
    appId: '1:138743338203:ios:32801e8365b0279a6028fe',
    messagingSenderId: '138743338203',
    projectId: 'beestore-ytu-9e44b',
    storageBucket: 'beestore-ytu-9e44b.appspot.com',
    iosBundleId: 'com.example.beeStore.RunnerTests',
  );
}
